# Generated by Django 2.0.7 on 2018-08-06 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('category', models.CharField(max_length=20, verbose_name='项目分类')),
                ('profile', models.CharField(max_length=300, verbose_name='项目简介')),
                ('details', models.TextField(verbose_name='项目详情')),
                ('requirements', models.TextField(verbose_name='技术要求')),
                ('skills_map', models.ImageField(blank=True, default='img/projects_profile/skills_map/default.jpg', null=True, upload_to='', verbose_name='技能图谱')),
                ('reference_case', models.CharField(max_length=300, verbose_name='参考案例')),
                ('recommended', models.IntegerField(choices=[(0, '未评级'), (1, '一颗星'), (2, '二颗星'), (3, '三颗星'), (4, '四颗星'), (5, '五颗星')], default=0, verbose_name='推荐指数')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='项目详情增加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='项目详情更新时间')),
            ],
            options={
                'verbose_name': '项目详情',
                'verbose_name_plural': '项目详情',
            },
        ),
    ]
